### ISSUE TITLE
Architectuur bestand maken

### ISSUE THREAD

**Issue by sw4kk3** [vives-project-xp/Letterklok#10]

**Comment by sw4kk3** [comment]
Input functie output diagram and req diagram made by cerian today... redelijk af kan nog later aan getweaked worden 
De Architectuur file is nog in de werking

**Comment by sw4kk3** [comment]
Deze is af

**Comment by declerckcerian** [comment]
Eerste versie van het architectuur bestand is klaar, er waren nog wat aanpassingen nodig nadat er fouten ontdekt werden:
-er werd een spanningsregelaar toegevoegd
-foutieve verbinding tussen de leds werd gecorrigeerd
-foutieve verbinding van de knoppen naar de ground werd gecorrigeerd
