### ISSUE TITLE
Ledstrip & MicroController stroom consumtie testen 

### ISSUE THREAD

**Issue by sw4kk3** [vives-project-xp/Letterklok#21]
Voor zeker te zijn voor dat onze voeding goe dgaat zijn gaan we een klein stuk ledstrip testen qua consumtie

**Comment by sw4kk3** [comment]
We Tested on a small scale of 31 leds

rood 25% | 5V | 4.5V-4.6V | 73mA | 337mW
rood 50% | 5V | 4.5V-4.6V | 113mA | 615mW
rood 75% | 5V | 4.5V-4.6V | 194mA | 895mW
rood 100% | 5V | 4.5V-4.6V | 253mA | 1.154W
wit 25% | 5V | 4.5V-4.6V | 221mA | 1.02W
wit 50% | 5V | 4.5V-4.6V | 381mA | 1.756W
wit 75 % | 5V | 4.5V-4.6V | 544mA | 2.5W
wit 100% | 5V | 4.5V-4.6V | 734mA | 3.376W


This are the values... so we calculated it for 1 strip of 5V
734mA / 31 * 30 * 5 = 3,56A voor 1 ledstrip

ESP verbruik 
3.3V
26mA
97mW

OOk inees testen hoe accuraat de real life clock:
Real time clock is van internet op controller met +- 0.5s delay en van mµ naar ledstrip is geen visueel verschil

**Comment by sw4kk3** [comment]
Moeten nu nog is testen met groote ledstrip

**Comment by declerckcerian** [comment]
We hebben vandaag een test gedaan waarbij we alle 300 LEDs van de ledstrip gebruikt hebben om zo het maximum verbruik op te meten:

Intensiteit | Verwachte Spanning | Opgemeten Spanning | Stroom | Vermogen

rood 25% | 5V | 4.5V-4.6V | 68mA | 3,067W
rood 50% | 5V | 4.5V-4.6V | 1,272A | 5,728W
rood 75% | 5V | 4.5V-4.6V | 1.863A | 8,385W
rood 100% | 5V | 4.5V-4.6V | 2,455A | 11,050W
wit 50% | 5V | 4.5V-4.6V | 2,290A | 10,30W
wit 100% | 5V | 4.5V-4.6V | 3,335A | 15W
witRGB 50% | 5V | 4.5V-4.6V | 3,130A | 14,090W
witRGB 100% | 5V | 4.5V-4.6V | 4,510A | 20,50W

**Comment by BramDe** [comment]
vandaag wat testen gedaan met de voeding van het labo lokaal en alles verloopt zonder probleem we geen dit nog eens bekijken wanneer onze eigen voeding aankomt.
