### ISSUE TITLE
Oplossing zoeken voor spanningsregelaar

### ISSUE THREAD

**Issue by declerckcerian** [vives-project-xp/Letterklok#23]

**Comment by sw4kk3** [comment]
We hebben een idee voor zeners der over te zetten om de ledstrips op de juiste spanning te hebben.
En voor de data van de microcontroller van 3.3 naar 5 gebruiken we een levelshifter

**Comment by sw4kk3** [comment]
![Image](https://github.com/vives-project-xp/Letterklok/assets/106929143/4db28b64-797c-43dd-98a0-66a489b4dcef)

**Comment by sw4kk3** [comment]
![IMG_4361](https://github.com/vives-project-xp/Letterklok/assets/106929143/523813b1-c96e-4320-b238-ff5b33246fca)

**Comment by sw4kk3** [comment]
<img width="310" alt="image" src="https://github.com/vives-project-xp/Letterklok/assets/106929143/aaf5048d-1b69-47fe-8407-f4aabfd3df27">
This is the new architecture shema this is how we will fix the 3.3v and 5v convertions shemas

**Comment by declerckcerian** [comment]
Nadat we advies hadden geraadpleegd van meneer Vereecke, kwamen we tot de conclusie dat we een component in onze architectuur moesten vervangen.

Eerst kozen we voor zenerdiode's, maar na veranderen van de voeding naar 5V waren deze niet meer nodig. Vervolgens waren we van plan een level shifter te gebruiken, maar dit is niet mogelijk om te gebruiken bij voeding.

Oplossing: -> spanningsregelaar step down voltage regulator 5v --> 3.3V, gevonden op Kiwi
