### ISSUE TITLE
Making program for full ledstrip

### ISSUE THREAD

**Issue by sw4kk3** [vives-project-xp/Letterklok#32]
Make the first edition of the final program where we controll the clock

**Comment by BramDe** [comment]
base off the program is made now we have to fine tune the led placement to proceed

**Comment by BramDe** [comment]
now we are testing wich leds need to be on for wich letter

**Comment by sw4kk3** [comment]
So we made the convertion to the full ledstrip with the time and the coresponding leds to display the time on the clock.
It works on SerialMonitor
