### ISSUE TITLE
Ledstrip uitrollen en op front display plaatsen

### ISSUE THREAD

**Issue by declerckcerian** [vives-project-xp/Letterklok#34]
We kijken eens hoe we de ledstrip precies gaan bevestigen op de klok, en we testen meteen ook of onze afmetingen goed zijn.

-Kijken of de verdeling van het licht goed zit
-Checken welke helderheid beter werkt

**Comment by BramDe** [comment]
ledstrip is getest en programma is aangepast aan de faceplate
